title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# url: https://just-the-docs.github.io

url: "https://libmint.github.io"
baseurl: "/docs"  # 저장소 이름을 'docs'로 만드셨다면 이렇게 적습니다.

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
